### ISSUE TITLE
Owner Restitution calc?

### ISSUE THREAD

**Issue by hyoung235** [agrahamg/VWBuybackCalculator#1]
Hi agrahamg,

When I get to the "trim" dropdown and select something the $5100 "adjustment" for owner restitution goes to zero. I tested it with other models but the same thing happens. Thanks! And thank you very much for setting up this calc. Best, Heather hyoung235@gmail.com

**Comment by Bigtuna00** [comment]
The $5,100 restitution is included in the total buyback amount listed in the official documents: https://www.ftc.gov/sites/default/files/pdf/att._1a_-_buyback_modification_table.pdf. The calculation you are referring to is probably just to make sure it's at least $5,100 which is the mandated minimum. If your mileage was lower, it would go up.

**Comment by agrahamg** [comment]
The adjustment row is extra money that you get if the amount you would be receiving would be less than $5,100. It disappears for you because the car row gets populated after selecting a trim level. It will show up on older cars with high mileage. 

Why that is happening is detailed on Further Adjustment in the mileage adjustment table (attachment 2) for your individual car. That document can be found [here](https://www.ftc.gov/enforcement/cases-proceedings/162-3006/volkswagen-group-america-inc) if you are curious.

**Comment by hyoung235** [comment]
Oh sorry. I thought you were going to calculate it on you online tool as
well. I just looked up the formula. It's 20% of the "Vehicle Value" plus
that $2,9xx.xx amount. Thanks!

**Comment by buffyp** [comment]
Any idea what happens if your car is totaled after the June 26th date?

**Comment by agrahamg** [comment]
@buffyp Sorry I'm unsure what happens.
