### ISSUE TITLE
Dollar goes up just by waiting around? 

### ISSUE THREAD

**Issue by kaydawdiddy** [agrahamg/VWBuybackCalculator#11]
The numbers on your calculator go up just by me adding more months past 9/15 for the buyback date. Is VW really paying people just to wait? I haven't read this anywhere else on the internet. I barely drive my car at all and the mileage won't change much before Sept. 2018....maybe 2000 miles a year, so this is actually a relevant question for me, although also just a curious one. Don't want to make a decision based on a bad algorithm :)

I have a 2012 jettawagen with power sunroof. 62000 miles. I walk to work and only use it for pleasure. May have 65000 by September 2018...

**Comment by agrahamg** [comment]
That is correct, each month you wait to turn it in VW assumes that you drove about 1000 miles per month. In your case with the limited amount of driving you do this could work out in your favor. One of the things you gain by turning it in sooner rather than later is knowing that you can turn your car in while it works. If you plan to wait till the last month and in that time have mechanical issues that prevent the car from being driven those would have to be fixed before the buyback, or if the car was to get totaled in some way that would also cause issues.

The algorithm is correct it's just a matter of how much risk you are willing to take. Either way best of luck with your jetta!

**Comment by kaydawdiddy** [comment]
Awesome! Thank you for making this calculator!
